// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ComoFirst.Model
{
    [Table("CheckList_Taches")]
    public partial class CheckListTaches
    {
        [Key]
        public int IdCheckList { get; set; }
        [Key]
        public int IdTaches { get; set; }

        [ForeignKey(nameof(IdCheckList))]
        [InverseProperty(nameof(CheckList.CheckListTaches))]
        public virtual CheckList IdCheckListNavigation { get; set; }
        [ForeignKey(nameof(IdTaches))]
        [InverseProperty(nameof(Taches.CheckListTaches))]
        public virtual Taches IdTachesNavigation { get; set; }
    }
}