// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ComoFirst.Model
{
    public partial class DbContextComofirst : DbContext
    {
        public DbContextComofirst()
        {
        }

        public DbContextComofirst(DbContextOptions<DbContextComofirst> options)
            : base(options)
        {
        }

        public virtual DbSet<CheckList> CheckList { get; set; }
        public virtual DbSet<CheckListTaches> CheckListTaches { get; set; }
        public virtual DbSet<Taches> Taches { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CheckList>(entity =>
            {
                entity.Property(e => e.NomCheckList).IsUnicode(false);
            });

            modelBuilder.Entity<CheckListTaches>(entity =>
            {
                entity.HasKey(e => new { e.IdCheckList, e.IdTaches });

                entity.HasOne(d => d.IdCheckListNavigation)
                    .WithMany(p => p.CheckListTaches)
                    .HasForeignKey(d => d.IdCheckList)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CheckList_Taches_CheckList");

                entity.HasOne(d => d.IdTachesNavigation)
                    .WithMany(p => p.CheckListTaches)
                    .HasForeignKey(d => d.IdTaches)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CheckList_Taches_Taches");
            });

            modelBuilder.Entity<Taches>(entity =>
            {
                entity.Property(e => e.LoginUtilisateur).IsUnicode(false);

                entity.Property(e => e.Text).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}