// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ComoFirst.Model
{
    public partial class Taches
    {
        public Taches()
        {
            CheckListTaches = new HashSet<CheckListTaches>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Text { get; set; }
        public bool Active { get; set; }
        [Required]
        [StringLength(15)]
        public string LoginUtilisateur { get; set; }

        [InverseProperty("IdTachesNavigation")]
        public virtual ICollection<CheckListTaches> CheckListTaches { get; set; }
    }
}